a = input ('enter what you want to know about me (name, age, etc) : ')
if (a == 'name') : print ('Koshish Tiwari') 
elif (a == 'age') : print ('18')
elif (a == 'class') : print ('Bachlors')
elif (a == 'school') : print ('Caldwell University')
else : print ('wrong entry')
